version: "3.7"

services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    restart: unless-stopped
    volumes:
      - ./docker/sqlite/:/db/ # see api/database.py, sqlite is mounted in /db/lil_analytics.db
    container_name: "lil_analytics_fastapi"
    ports:
    - "${FASTAPI_PORT}:5000"
    networks:
      - internal

  bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    restart: unless-stopped
    container_name: "lil_analytics_bot"
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - COMMAND_PREFIX=${COMMAND_PREFIX}
      - STATUS_MESSAGE=${STATUS_MESSAGE}
      - INVITE_LINK=${INVITE_LINK}
      - GITHUB_LINK=${GITHUB_LINK}
    ports:
    - "${BOT_PORT}:80"
    networks:
      - web

# https://stackoverflow.com/questions/61112808/correct-nginx-conf-loadbalancing-to-uvicorn-fastapi-with-docker-compose:
  nginx:
    image: nginx:latest
    ports:
      - "${NGINX_PORT}:8080"
      - "443:443"
    volumes:
      - ./docker/nginx_config.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    environment:
      - NGINX_PORT=${NGINX_PORT}
    networks:
      - web
      - internal

networks:
  internal:
    external: false
  web:
    external: true

