version: "3.7"

services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile_api
    restart: unless-stopped
    volumes:
      - ./docker/sqlite/:/db/ # see api/database.py, sqlite is mounted in /db/lil_analytics.db
    container_name: "lil_analytics_fastapi"
    environment:
      - MONGO_USER=${MONGO_USER}
      - MONGO_PSW=${MONGO_PASSWORD}
    ports:
    - "${FASTAPI_PORT}:5000"
    networks:
      - web
      - internal

  bot:
    build:
      context: .
      dockerfile: docker/Dockerfile_bot
    restart: unless-stopped
    container_name: "lil_analytics_bot"
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - COMMAND_PREFIX=${COMMAND_PREFIX}
      - STATUS_MESSAGE=${STATUS_MESSAGE}
      - INVITE_LINK=${INVITE_LINK}
      - GITHUB_LINK=${GITHUB_LINK}
    ports:
    - "80:80"
    networks:
      - web

networks:
  internal:
    external: false
  web:
    external: true

