version: "3.7"

services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    restart: unless-stopped
    environment:
      - FASTAPI_KEY=${FASTAPI_KEY}
    volumes:
      # See api/database.py, sqlite is mounted in /db/lil_analytics.db
      - ./docker/sqlite/:/db/
    container_name: "lil_analytics_fastapi"
    ports:
    - "${FASTAPI_PORT}:5000"
    networks:
      - internal
  bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    restart: unless-stopped
    container_name: "lil_analytics_bot"
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - BOT_OWNER_ID=${BOT_OWNDER_ID}
      - COMMAND_PREFIX=${COMMAND_PREFIX}
      - STATUS_MESSAGE=${STATUS_MESSAGE}
      - INVITE_LINK=${INVITE_LINK}
      - GITHUB_LINK=${GITHUB_LINK}
      - FASTAPI_KEY=${FASTAPI_KEY}
    ports:
    - "${BOT_PORT}:80"
    networks:
      - web
      - internal
#  nginx:
#    image: nginx:1.19.6-alpine
#    restart: unless-stopped
#    volumes:
#      # If you want to use variables, templates are needed. Default.conf wont work!
#      # https://hub.docker.com/_/nginx
#      - ./docker/templates:/etc/nginx/templates
#    environment:
#      - NGINX_PORT=${NGINX_PORT}
#      - DOMAIN=${DOMAIN}
#    ports:
#      - "${NGINX_PORT}:${NGINX_PORT}"
#      - "443:443"
#    networks:
#      - web
#      - internal

networks:
  internal:
    external: false
  web:
    external: true

